### ISSUE TITLE
Fix Keys on AWT target

### ISSUE THREAD

**Issue by soywiz** [korlibs/korgw#33]

**Comment by RezMike** [comment]
This issue was created after this conversation in slack: https://kotlinlang.slack.com/archives/G014YN8Q7TK/p1592347162055600
The problem was that `onKeyTyped` wasn't called when typing non-symbol keys (arrows, Ctrl, Shift, Enter, etc.)
But this is the correct behavior in AWT (check [this](https://docs.oracle.com/javase/7/docs/api/java/awt/event/KeyEvent.html)), so this issue is no longer relevant, and I'm closing it.
